### ISSUE TITLE
Thiết kế DB

### ISSUE THREAD

**Issue by hoainv-relipasoft** [relipasoft/religram-api-k3#1]
**Mô tả lý do TẠI SAO bạn muốn có chức năng này**
- Phân tích thiết kế yêu cầu của khách hàng -> tạo DB có thể đáp ứng được những yêu cầu đó

**Mô tả cách triển khai bạn hình dung**
- Đọc những chức năng cần làm
- Xem mockup và yêu cầu cụ thể trong mockup
- Thiết kế DB làm sao chuẩn chỉ, ko bị dư thừa dữ liệu

**Mô tả kết quả nghiệm thu bạn mong muốn**
- Có ERD đáp ứng chuẩn ko dư thừa dữ liệu
- Đáp ứng được yêu cầu của khách hàng
- Có tính mở rộng sau này

**Note**
- Link mockup: https://drive.google.com/drive/folders/1BZ4-IiPLdb0F1Zap8ywFiauI-QqsfCLV
- Link nội dung yêu cầu: https://www.mindmeister.com/1246628932?t=WwR7Puj39I
Chú ý làm phần basic thôi nhé.

**Comment by duycv-relipasoft** [comment]
![DB_Religram](https://user-images.githubusercontent.com/53416403/62096077-a393c400-b2ac-11e9-865a-5625d7682777.png)

**Comment by duycv-relipasoft** [comment]
Theo em thì có các thực thể sau:
User, Post, Comment, Follow, Image.
- User chứa thông tin về người dùng
- Post chứa thông tin về bài post
- Comment chứa thông tin về comment
- Follow chứa danh sách người mà user follow
- Image chứa thông tin về ảnh

User có các trường:
- email
- full name
- user name
- password
- avatar chứa tên ảnh avatar

Post
- content: Nội dung bài post
- like: số like
- time: thời gian post

Comment
- content: Nội dung comment

Image:
- name: chứa tên ảnh

Follow:
- follow_id: Chứa id của người mình follow

Mối quan hệ:
- 1 User có nhiều Post
- 1 User có nhiều Comment
- 1 User follow nhiều người
- 1 Post có nhiều Comment
- 1 Post có nhiều Image

**Comment by hoainv-relipasoft** [comment]
Nếu chỉ hiển thi số like thì nếu anh muốn check khi vào trang home, anh đã like bài nào, chưa like bài nào thì làm thế nào nhỉ? @duycv-relipasoft :smile:

**Comment by duycv-relipasoft** [comment]
Thế phải thêm bảng nữa để lưu lại cái này anh ạ. :) @hoainv-relipasoft

**Comment by duycv-relipasoft** [comment]
![DB_Religram_ver2](https://user-images.githubusercontent.com/53416403/62105567-f4b3b000-b2cc-11e9-968d-61743f0552e7.png)

**Comment by duycv-relipasoft** [comment]
Update thêm bảng like và liên kết giữa bảng like với post và like với user
![DB_Religram_ver3](https://user-images.githubusercontent.com/53416403/62105889-de5a2400-b2cd-11e9-85b5-e7d371595f2c.png)

**Comment by hungvv-relipa** [comment]
![Untitled1](https://user-images.githubusercontent.com/53416423/62107979-0e57f600-b2d3-11e9-9d5c-ad1185e9f0bc.png)

**Comment by hungvv-relipa** [comment]
Các trường thông tin của User là các quan hệ 2 chiều 1-1

Đối với các bài Post thì gồm 2 thành phần
     1. Nội dung: Data (Images, Videos là bắt buộc), Times, Status,..
     2. Tương tác: (Like, Comments, Shares) và chứa 1 thông tin về ID của người tương tác.

Bảng thông báo: Notifications
     Có quan hệ 1-1 đơn chiều với các table: Following, Interactive chứa thông tin: ID (của người Follow), ID Post và ID User ( đối với người Comment hay Like)

**Comment by hoainv-relipasoft** [comment]
> 2. Tương tác: (Like, Comments, Shares) và chứa 1 thông tin về ID của người tương tác.

@hungvv-relipa cái bảng tương tác này là như nào em nhỉ? cả like + comment + share em cùng cho vào trong đó à? như vậy thì khi lọc những comment của 1 bài post, đếm số like, comment, check xem mình có like bài post đó hay không thì có vất lắm ko nhỉ?

**Comment by hungvv-relipa** [comment]
Đúng rồi anh... Em viết chung nó vào cho dễ nhìn.
Còn về cơ bản e sẽ tách ra thành 3 thành phần Like, Share, Comments, riêng.
Cả cái bảng Notifications cũng thế ạ. Like, Share, Comments, Follow.

**Comment by hungvv-relipa** [comment]
Còn một cái nữa là mối quan hệ giữa User và Notification ko phải là mối quan hệ 2 chiều như hình vẽ... Nó là quan hệ 1 chiều từ phía User thôi, nãy e quên Save nó lại @@

**Comment by hoainv-relipasoft** [comment]
> Còn về cơ bản e sẽ tách ra thành 3 thành phần Like, Share, Comments, riêng.
Sao ko tách luôn em nhỉ? mình làm là thiết kế DB chuẩn chỉnh luôn để còn bắt tay xây dựng entity, table trong code luôn mà. ko bây giờ thì là bao giờ làm nhỉ? :smiley: 
còn notification thì pharse này tạm thời mình chưa làm nên chưa cần bảng này nhé. 

Nhớ đọc và bám vào bảng mind map anh gửi và hình mock up

**Comment by hungvv-relipa** [comment]
Bỏ thông báo và tách riêng.

![Untitled1](https://user-images.githubusercontent.com/53416423/62119200-3fdbbc00-b2e9-11e9-88f4-bb0d2cb01ff3.png)

**Comment by duycv-relipasoft** [comment]
@hungvv-relipa @hoainv-relipasoft 
![DB_Religram_ver5](https://user-images.githubusercontent.com/53416403/62179905-4f561600-b378-11e9-93ea-69e4e0011cf2.png)

**Comment by hoainv-relipasoft** [comment]
Ở các bảng nên thêm trường `created_at` và `updated_at` vào để sau này tiện order nhé @duycv-relipasoft @hungvv-relipa

**Comment by hoainv-relipasoft** [comment]
cái hashtag thì có vẻ chưa ổn lắm thì phải. xem lại bảng hashtag nhé. vì thằng hashtag thì ko cần user id đâu. quan trọng là tên hashtag là gì nữa cơ :smile:

**Comment by duycv-relipasoft** [comment]
@hoainv-relipasoft  @hungvv-relipa 
![DB_Religram_ver6](https://user-images.githubusercontent.com/53416403/62180518-8a594900-b37a-11e9-97ee-d4c487c34e4f.png)

**Comment by hoainv-relipasoft** [comment]
uhm, bản này có vẻ ổn hơn rồi đấy. thêm cả count_like vào bài post nữa nhé

**Comment by duycv-relipasoft** [comment]
Update create_at, update_at và sửa bảng hashtag @hoainv-relipasoft @hungvv-relipa 
![DB_Religram_ver7](https://user-images.githubusercontent.com/53416403/62180607-d906e300-b37a-11e9-8321-7c4d92f65332.png)

**Comment by hoainv-relipasoft** [comment]
ok. task này done nhé. chuyển qua task tiếp theo đi các em =))
