### ISSUE TITLE
Dựng khung project

### ISSUE THREAD

**Issue by hoainv-relipasoft** [relipasoft/religram-api-k3#2]
**Mô tả lý do TẠI SAO bạn muốn có chức năng này**
- Cần có khung source code đẹp, dễ đọc, dễ mở rộng, maintenance

**Mô tả cách triển khai bạn hình dung**

**Mô tả kết quả nghiệm thu bạn mong muốn**
- Dựng project Java Spring Boot
- Spring mvc
- Spring security
- Spring REST
- JPA
- Có JUnit
- Có các lớp, package common, abstract, interface để sau này kế thừa và implement

**Note**

**Comment by duycv-relipasoft** [comment]
![image](https://user-images.githubusercontent.com/53416403/62109729-1ade4d80-b2d7-11e9-9120-2af065537cfc.png)
Có các gói:
- abstract: Chứa các lớp abstract dùng chung
- common: Chứa các lớp dùng chung
- interface: Chứa các lớp interface dùng chung
- Mỗi package entity, rest, jpa đều có 2 package con là interface và implement dùng để tách biệt sự trừu tượng và chi tiết đồng thời thuận lợi cho việc tái sử dụng.
=> Nếu mình cần các lớp rest thì chỉ cần copy package rest về là xong. Hoặc nếu mình muốn implement cái mới thì chỉ cần xem lớp trong interface là xong.

**Comment by duycv-relipasoft** [comment]
![image](https://user-images.githubusercontent.com/53416403/62438419-8316ae80-b771-11e9-8456-e70aab1ae10e.png)
- controller chứa các rest controller
- dao chứa interface của dao
- dao.impl chứa các implement của dao
- entity.database: chứa các entity mapping với database
- entity.request: chứa các entity request
- entity.response: chứa các entity response
- exception.entity: chứa các entity exception
- exception.handler: chứa các xử lý exception
- service chứa interface của service
- service.impl: chứa các implement của service
