### ISSUE TITLE
Tạo API đăng ký user

### ISSUE THREAD

**Issue by hoainv-relipasoft** [relipasoft/religram-api-k3#3]
**Mô tả lý do TẠI SAO bạn muốn có chức năng này**

**Mô tả cách triển khai bạn hình dung**

**Mô tả kết quả nghiệm thu bạn mong muốn**
- Có API theo thiết kế như tài liệu: https://religram.relipa-test.online/api-doc/#/auth/signup

**Note**

**Comment by duycv-relipasoft** [comment]
Các phần kia em xử lý xong rồi ạ. Phần token xử lý sao anh? @hoainv-relipasoft
